### ISSUE TITLE
Command in python_script.conf

### ISSUE THREAD

**Issue by sumantabose** [DataKrewTech/Modbus-Hevea#1]
@arjun289 Why is there a space after python3 in [`python_script.conf`](https://github.com/DataKrewTech/Modbus-Hevea/blob/master/python_script.conf) as below:

`command=/usr/bin/python3 /home/pi/banner.py`

**Comment by arjun289** [comment]
These are two separate commands `/usr/bin/python3` is python path and the second is file to run
